apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-microservice.fullname" . }}-secret
  labels:
    {{- include "order-microservice.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.spring.datasource.username | b64enc }}
  password: {{ .Values.spring.datasource.password | b64enc }}